- name: Workflow Dispatch Plus
  # You may pin to the exact commit or the version.
  # uses: pauldraper/workflow-dispatch@e654f7d9b7cdb02a6a3bb2a6d288b54e507075e0
  uses: pauldraper/workflow-dispatch@v1.5
  with:
    # JSON object of inputs
    inputs: # optional, default is {}
    # Name of input for this workflow's URL
    marker-input: # optional
    # Repository owner and name
    repo: # optional, default is ${{ github.repository }}
    # Ref
    ref: # optional, default is ${{ github.ref }}
    # Personal access token, see https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/creating-a-personal-access-token
    token: # optional, default is ${{ github.token }}
    # Whether to wait for
    wait: # optional, default is false
    # Workflow file path
    workflow: 
